apiVersion: v1
kind: PersistentVolume
metadata:
  name: review-db-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  storageClassName: review-db-class
  # A hostPath volume mounts a file or directory from the host node's file system into your pod
  hostPath:
    path: "/mnt/data/review"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: review-db-pvc
spec:
  # map to storageClassName in pv
  storageClassName: review-db-class
  resources:
    requests:
      storage: 500Mi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: review-db-config
data:
  POSTGRES_DB: review
  POSTGRES_USER: admin
  POSTGRES_PASSWORD: admin
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: review-db
spec:
  selector:
    matchLabels:
      app: review-db # has to match spec.template.metadata.labels
  serviceName: review-db
  replicas: 1
  template:
    metadata:
      labels: # has to match spec.selector.matchLabels
        app: review-db
    spec:
      containers:
      - name: review-db
        image: postgres:15.1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: review-db-config
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: review-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: review-db
spec:
  type: NodePort
  selector:
    app: review-db
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30017