// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.15.0

package repository

import ()

type Image struct {
	ID       int64
	ReviewID int64
	ImageUrl string
}

type Review struct {
	ID        int64
	UserID    int64
	ProductID int64
	NumStar   int32
}
